apiVersion: v1
kind: ConfigMap
metadata:
  name: ppa-predictions-config
  namespace: ppa
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
data:
  DEBUG: "{{.Values.configuration.debug}}"
  MAIL_RECIPIENT_CONS: "{{.Values.configuration.debug}}"
  SEND_PREDICTIONS_ENABLED: "{{.Values.configuration.debug}}"
  SMTP_HOST: "{{.Values.configuration.debug}}"
  SMTP_PORT: "{{.Values.configuration.debug}}"
  SMTP_EMAIL: "{{.Values.configuration.debug}}"
  UPDATE_CRON: "{{.Values.configuration.debug}}"
