apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ppa-prediction-secrets
  namespace: ppa
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/{{ .Values.onepassword.vault }}/items/aks-ppa-prediction-secrets"
